name: 'CI'

on:
  push:
    branches:
      - master
  pull_request_target: {}

jobs:
  test-v2:
    name: Test v2
    runs-on: ubuntu-latest
    continue-on-error: true
    strategy:
      matrix:
        go_version:
          - ~1.11
          - ~1.12
          - ~1.16
    defaults:
      run:
        working-directory: v2
    permissions:
      contents: read
    env:
      GCLOUD_VERSION: "392.0.0"
      GO111MODULE: "on"
      GOOGLE_CLOUD_PROJECT: "unittest"
    steps:
      - uses: actions/checkout@v3
        with:
          # pull_request_target の場合PRのhead(場合によってはvulnerable)、そうじゃなければcontextのsha
          ref: ${{ github.event.pull_request.head.sha || github.sha }}
      - uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go_version }}
      - name: Cache go dependencies
        uses: actions/cache@v3
        id: cache
        with:
          key: ${{ runner.os }}-go-cache-r1-v2-${{ matrix.go_version }}-${{ hashFiles('**/go.mod') }}-${{ hashFiles('**/go.sum') }}
          path: |-
            ~/go/pkg/mod
      - name: Prepare dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: |-
          ./setup.sh
      - uses: google-github-actions/setup-gcloud@v0
        with:
          version: ${{ env.GCLOUD_VERSION }}
          project_id: ${{ env.DATASTORE_PROJECT_ID }}
          install_components: "app-engine-go"
      - name: Run tests
        run: |-
          ./test.sh -v -timeout 4m
